###peticion get - todas las Recetas
get http://localhost:3000/api/recipes

###peticion get - una Receta con sus imagenes
get http://localhost:3000/api/recipes/3

###peticion get - recetas con sus imagenes y que cumplan con la busqueda
get http://localhost:3000/api/recipes/buscar?termino=flan

###peticion post - crear una Receta
Post http://localhost:3000/api/recipes
Content-Type: application/json

{
    "name_recipe": 303,
    "tipo": "Room Deluxe",
    "description": "Suite de lujo con jacuzzi y vista a la ciudad",
    "price": 250.00,
    "time": 2,
    "status": "disponible" 
}

###peticion put - Actualizar una Receta
Put http://localhost:3000/api/recipes/1
Content-Type: application/json

{
    "id": 1,
    "name_recipe": 303,
    "tipo": "Room Deluxe",
    "description": "Suite de lujo con jacuzzi y vista a la ciudad",
    "price": 250.00,
    "time": 2,
    "status": "disponible" 
}

###peticion delete - eliminar una Receta
DELETE http://localhost:3000/api/recipes/1
Content-Type: application/json

{
    "id": 1
}

###peticion post - Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "correo":"juan@chef.com",
    "password":"chef123"
}

###peticion post - Register
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "nombre":"rascael Bermudez",
    "correo":"rasca@chef.com",
    "password":"$2b$10$JTzDdNKi8yhnEdrh0q4xKe6o/DeTmTXaJ10j7aaZ3/Xli1qqx1DW2",
    "rol":"chef"
}